-- MySQL Script generated by MySQL Workbench
-- Sun May 20 20:22:18 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema a20151258
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `a20151258` ;

-- -----------------------------------------------------
-- Schema a20151258
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `a20151258` DEFAULT CHARACTER SET utf8 ;
USE `a20151258` ;

-- -----------------------------------------------------
-- Table `a20151258`.`LOCAL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `a20151258`.`LOCAL` ;

CREATE TABLE IF NOT EXISTS `a20151258`.`LOCAL` (
  `idLOCAL` INT NOT NULL AUTO_INCREMENT,
  `telefonoLocal` VARCHAR(15) NOT NULL,
  `direccionLocal` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`idLOCAL`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `a20151258`.`ALM_ALMACEN`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `a20151258`.`ALM_ALMACEN` ;

CREATE TABLE IF NOT EXISTS `a20151258`.`ALM_ALMACEN` (
  `idAlmacen` INT NOT NULL AUTO_INCREMENT,
  `habilitado` TINYINT NOT NULL,
  `LOCAL_idLOCAL` INT NOT NULL,
  PRIMARY KEY (`idAlmacen`),
  INDEX `fk_ALM_ALMACEN_LOCAL1_idx` (`LOCAL_idLOCAL` ASC),
  CONSTRAINT `fk_ALM_ALMACEN_LOCAL1`
    FOREIGN KEY (`LOCAL_idLOCAL`)
    REFERENCES `a20151258`.`LOCAL` (`idLOCAL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `a20151258`.`Producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `a20151258`.`Producto` ;

CREATE TABLE IF NOT EXISTS `a20151258`.`Producto` (
  `idProducto` INT NOT NULL,
  `codProducto` VARCHAR(10) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `habilitado` TINYINT NOT NULL,
  `descripcionProd` VARCHAR(100) NULL,
  PRIMARY KEY (`idProducto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `a20151258`.`ALM_PRODUCTO_ALMACEN`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `a20151258`.`ALM_PRODUCTO_ALMACEN` ;

CREATE TABLE IF NOT EXISTS `a20151258`.`ALM_PRODUCTO_ALMACEN` (
  `Almacen_idAlmacen` INT NOT NULL,
  `Producto_idProducto` INT NOT NULL,
  `cantidadAlmacenada` INT NOT NULL,
  PRIMARY KEY (`Producto_idProducto`, `Almacen_idAlmacen`),
  INDEX `fk_ProductoAlmacen_Producto1_idx` (`Producto_idProducto` ASC),
  CONSTRAINT `fk_ProductoAlmacen_Almacen`
    FOREIGN KEY (`Almacen_idAlmacen`)
    REFERENCES `a20151258`.`ALM_ALMACEN` (`idAlmacen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ProductoAlmacen_Producto1`
    FOREIGN KEY (`Producto_idProducto`)
    REFERENCES `a20151258`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `a20151258`.`ALM_INGRESO_PRODUCTO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `a20151258`.`ALM_INGRESO_PRODUCTO` ;

CREATE TABLE IF NOT EXISTS `a20151258`.`ALM_INGRESO_PRODUCTO` (
  `idIngresoProducto` INT NOT NULL AUTO_INCREMENT,
  `Almacen_idAlmacen` INT NOT NULL,
  `fechaIngreso` DATETIME NOT NULL,
  `observaciones` VARCHAR(256) NULL,
  `idLocalEmisor` INT NOT NULL,
  PRIMARY KEY (`idIngresoProducto`),
  INDEX `fk_IngresoProducto_Almacen1_idx` (`Almacen_idAlmacen` ASC),
  INDEX `fk_ALM_INGRESO_PRODUCTO_LOCAL1_idx` (`idLocalEmisor` ASC),
  CONSTRAINT `fk_IngresoProducto_Almacen1`
    FOREIGN KEY (`Almacen_idAlmacen`)
    REFERENCES `a20151258`.`ALM_ALMACEN` (`idAlmacen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ALM_INGRESO_PRODUCTO_LOCAL1`
    FOREIGN KEY (`idLocalEmisor`)
    REFERENCES `a20151258`.`LOCAL` (`idLOCAL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `a20151258`.`ALM_SALIDA_PRODUCTO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `a20151258`.`ALM_SALIDA_PRODUCTO` ;

CREATE TABLE IF NOT EXISTS `a20151258`.`ALM_SALIDA_PRODUCTO` (
  `idSalidaProducto` INT NOT NULL AUTO_INCREMENT,
  `Almacen_idAlmacen` INT NOT NULL,
  `fechaSalida` DATETIME NOT NULL,
  `observaciones` VARCHAR(256) NULL,
  `idLocalDestino` INT NOT NULL,
  PRIMARY KEY (`idSalidaProducto`),
  INDEX `fk_SalidaProducto_Almacen1_idx` (`Almacen_idAlmacen` ASC),
  INDEX `fk_ALM_SALIDA_PRODUCTO_LOCAL1_idx` (`idLocalDestino` ASC),
  CONSTRAINT `fk_SalidaProducto_Almacen1`
    FOREIGN KEY (`Almacen_idAlmacen`)
    REFERENCES `a20151258`.`ALM_ALMACEN` (`idAlmacen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ALM_SALIDA_PRODUCTO_LOCAL1`
    FOREIGN KEY (`idLocalDestino`)
    REFERENCES `a20151258`.`LOCAL` (`idLOCAL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `a20151258`.`ALM_LINEA_SALIDA_PRODUCTO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `a20151258`.`ALM_LINEA_SALIDA_PRODUCTO` ;

CREATE TABLE IF NOT EXISTS `a20151258`.`ALM_LINEA_SALIDA_PRODUCTO` (
  `idLineaSalidaProducto` INT NOT NULL AUTO_INCREMENT,
  `SalidaProducto_idSalidaProducto` INT NOT NULL,
  `cantidadSalida` INT NOT NULL,
  `observaciones` VARCHAR(128) NULL,
  `Producto_idProducto` INT NOT NULL,
  PRIMARY KEY (`idLineaSalidaProducto`),
  INDEX `fk_ALM_LINEA_SALIDA_PRODUCTO_SalidaProducto1_idx` (`SalidaProducto_idSalidaProducto` ASC),
  INDEX `fk_ALM_LINEA_SALIDA_PRODUCTO_Producto1_idx` (`Producto_idProducto` ASC),
  CONSTRAINT `fk_ALM_LINEA_SALIDA_PRODUCTO_SalidaProducto1`
    FOREIGN KEY (`SalidaProducto_idSalidaProducto`)
    REFERENCES `a20151258`.`ALM_SALIDA_PRODUCTO` (`idSalidaProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ALM_LINEA_SALIDA_PRODUCTO_Producto1`
    FOREIGN KEY (`Producto_idProducto`)
    REFERENCES `a20151258`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `a20151258`.`ALM_LINEA_INGRESO_PRODUCTO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `a20151258`.`ALM_LINEA_INGRESO_PRODUCTO` ;

CREATE TABLE IF NOT EXISTS `a20151258`.`ALM_LINEA_INGRESO_PRODUCTO` (
  `idLineaIngresoProducto` INT NOT NULL AUTO_INCREMENT,
  `IngresoProducto_idIngresoProducto` INT NOT NULL,
  `cantidadIngreso` INT NOT NULL,
  `observaciones` VARCHAR(128) NULL,
  `Producto_idProducto` INT NOT NULL,
  PRIMARY KEY (`idLineaIngresoProducto`),
  INDEX `fk_ALM_LINEA_INGRESO_PRODUCTO_IngresoProducto1_idx` (`IngresoProducto_idIngresoProducto` ASC),
  INDEX `fk_ALM_LINEA_INGRESO_PRODUCTO_Producto1_idx` (`Producto_idProducto` ASC),
  CONSTRAINT `fk_ALM_LINEA_INGRESO_PRODUCTO_IngresoProducto1`
    FOREIGN KEY (`IngresoProducto_idIngresoProducto`)
    REFERENCES `a20151258`.`ALM_INGRESO_PRODUCTO` (`idIngresoProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ALM_LINEA_INGRESO_PRODUCTO_Producto1`
    FOREIGN KEY (`Producto_idProducto`)
    REFERENCES `a20151258`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
