-- MySQL Script generated by MySQL Workbench
-- Thu Apr 26 04:14:50 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema a20151258
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema a20151258
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `a20151258` DEFAULT CHARACTER SET utf8 ;
USE `a20151258` ;

-- -----------------------------------------------------
-- Table `a20151258`.`Sucursal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `a20151258`.`Sucursal` (
  `idSucursal` VARCHAR(10) NOT NULL,
  `direccion` VARCHAR(45) NULL,
  `telefono` VARCHAR(10) NULL,
  PRIMARY KEY (`idSucursal`))
ENGINE = InnoDB
COMMENT = 'Falta conectar con clientes y con vehiculos.';


-- -----------------------------------------------------
-- Table `a20151258`.`Almacen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `a20151258`.`Almacen` (
  `idAlmacen` VARCHAR(10) NOT NULL,
  `Sucursal_idSucursal` VARCHAR(10) NOT NULL,
  `habilitado` TINYINT NULL,
  PRIMARY KEY (`idAlmacen`),
  INDEX `fk_Almacen_Sucursal1_idx` (`Sucursal_idSucursal` ASC),
  CONSTRAINT `fk_Almacen_Sucursal1`
    FOREIGN KEY (`Sucursal_idSucursal`)
    REFERENCES `a20151258`.`Sucursal` (`idSucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `a20151258`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `a20151258`.`Producto` (
  `idProducto` VARCHAR(10) NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `habilitado` TINYINT NULL,
  PRIMARY KEY (`idProducto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `a20151258`.`ProductoAlmacen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `a20151258`.`ProductoAlmacen` (
  `Almacen_idAlmacen` VARCHAR(10) NOT NULL,
  `Producto_idProducto` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`Almacen_idAlmacen`, `Producto_idProducto`),
  INDEX `fk_ProductoAlmacen_Producto1_idx` (`Producto_idProducto` ASC),
  CONSTRAINT `fk_ProductoAlmacen_Almacen`
    FOREIGN KEY (`Almacen_idAlmacen`)
    REFERENCES `a20151258`.`Almacen` (`idAlmacen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ProductoAlmacen_Producto1`
    FOREIGN KEY (`Producto_idProducto`)
    REFERENCES `a20151258`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `a20151258`.`IngresoProducto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `a20151258`.`IngresoProducto` (
  `idIngresoProducto` VARCHAR(10) NOT NULL,
  `Producto_idProducto` VARCHAR(10) NOT NULL,
  `Almacen_idAlmacen` VARCHAR(10) NOT NULL,
  `cantidadIngreso` INT NOT NULL,
  `fechaIngreso` DATETIME NOT NULL,
  PRIMARY KEY (`idIngresoProducto`, `Producto_idProducto`, `Almacen_idAlmacen`),
  INDEX `fk_IngresoProducto_Almacen1_idx` (`Almacen_idAlmacen` ASC),
  CONSTRAINT `fk_IngresoProducto_Producto1`
    FOREIGN KEY (`Producto_idProducto`)
    REFERENCES `a20151258`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_IngresoProducto_Almacen1`
    FOREIGN KEY (`Almacen_idAlmacen`)
    REFERENCES `a20151258`.`Almacen` (`idAlmacen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `a20151258`.`SalidaProducto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `a20151258`.`SalidaProducto` (
  `idSalidaProducto` VARCHAR(10) NOT NULL,
  `cantidadSalida` INT NOT NULL,
  `fechaSalida` DATETIME NOT NULL,
  `Producto_idProducto` VARCHAR(10) NOT NULL,
  `Almacen_idAlmacen` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idSalidaProducto`, `Producto_idProducto`, `Almacen_idAlmacen`),
  INDEX `fk_SalidaProducto_Producto1_idx` (`Producto_idProducto` ASC),
  INDEX `fk_SalidaProducto_Almacen1_idx` (`Almacen_idAlmacen` ASC),
  CONSTRAINT `fk_SalidaProducto_Producto1`
    FOREIGN KEY (`Producto_idProducto`)
    REFERENCES `a20151258`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SalidaProducto_Almacen1`
    FOREIGN KEY (`Almacen_idAlmacen`)
    REFERENCES `a20151258`.`Almacen` (`idAlmacen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
